baseURL = "https://ddarlaa.github.io/front_laba2/"
languageCode = 'ru-ru'
title = 'Тестовый сервер Дарлы на Hugo'
theme = 'hextra'
## markup configuration
[markup]

    [markup.highlight]
        ## Enable code fence highlighting
        codeFences = true
        ## Use hugo-brewm classes for verbatim styling
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true
      
    [markup.goldmark.extensions]
        [markup.goldmark.extensions.passthrough]
            ## Enable internal math render
            enable = true
            ## Set math delimiters
            [markup.goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$'], ['\begin{equation}', '\end{equation}'], ['\begin{align}', '\end{align}']]
                inline = [['\(', '\)'], ['$', '$'] ]
## Sitemap configuration
[sitemap]
    ## Change frequency setting (will affect posts listings layout): 'always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never'
    changeFreq = 'monthly'

[menu]
  [[menu.main]]
    name = "Блог"
    pageRef = "/blog"
    weight = 1
